# Generated by Django 5.1.3 on 2024-11-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
